[package]
name = "bender"
version = "0.7.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serde_json = "1.0"

futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1.12"
tokio-process = "0.1.5"
tokio-timer = "0.1"

clap = "2.20.0"
semver = "0.5.1"
blake2 = "0.7.0"
typed-arena = "1.3.0"
