[package]
name = "bender"
version = "0.13.3"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>", "Andreas Kurth <akurth@iis.ee.ethz.ch>"]
description = "A dependency management tool for hardware projects."
readme = "README.md"
license = "Apache-2.0 OR MIT"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
serde_json = "1.0"

futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1.12"
tokio-process = "0.1.5"
tokio-timer = "0.1"

clap = "2.20.0"
semver = "0.9.0"
blake2 = "0.7.0"
typed-arena = "1.3.0"
dirs = "1"
pathdiff = "0.1"

itertools = "0.8.0"

atty = "0.2"
